{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4bb8b86e-45a6-43fc-a280-62ade73709d4",
   "metadata": {},
   "outputs": [],
   "source": [
    "#deadlock "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "ed891b9c-7bc8-4c62-bbf1-1855472920bd",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-111 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "Exception in thread Thread-112 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "Exception in thread Thread-113 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "Exception in thread Thread-114 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "Exception in thread Thread-115 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-116 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "Exception in thread Thread-117 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "Exception in thread Thread-118 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-119 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-120 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "Exception in thread Thread-121 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "Exception in thread Thread-122 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-123 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "Exception in thread Thread-124 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "Exception in thread Thread-125 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "Exception in thread Thread-126 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-127 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "Exception in thread Thread-128 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "Exception in thread Thread-129 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-130 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "Exception in thread Thread-131 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "Exception in thread Thread-132 (test1):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 1038, in _bootstrap_inner\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self.run()\n",
      "  File \"C:\\Users\\shahid jamal\\anaconda3\\Lib\\threading.py\", line 975, in run\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\shahid jamal\\AppData\\Local\\Temp\\ipykernel_13632\\1893282551.py\", line 6, in test1\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n",
      "UnboundLocalError: cannot access local variable 'y_var' where it is not associated with a value\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import threading\n",
    "y_var=1\n",
    "def test1(x):\n",
    "    \n",
    "        y_var=y_var*2\n",
    "        print(\"value of x %d and value of y_var %d \" %(x,y_var)) \n",
    "        time.sleep(1)\n",
    "thread1=[threading.Thread(target=test1,args=(a,)) for a in [1,2,3,4,5,6,7,8]]\n",
    "thread2=[threading.Thread(target=test1,args=(b,)) for b in [9,10,11,12,13,14,15]]\n",
    "thread3=[threading.Thread(target=test1,args=(c,)) for c in [16,17,18,19,20,21,22]]\n",
    "for s in thread1:\n",
    "    s.start()\n",
    "for m in thread2:\n",
    "    m.start()\n",
    "for n in thread3:\n",
    "    n.start()\n",
    "   \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d36b22db-a30c-42ad-9370-b07fdfda7865",
   "metadata": {},
   "outputs": [],
   "source": [
    "#so when many threads running at same time then there occurs a race condition which leads to deadlock."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f033e857-9221-4365-a4ab-f140586d5a31",
   "metadata": {},
   "outputs": [],
   "source": [
    "#to get rid of this we have to use lock function.it provides exclusive access to shared resources."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "8574992b-6679-43ea-91b1-485f8d963d4a",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "value of x 1 and value of y_var 2 \n",
      "value of x 2 and value of y_var 4 \n",
      "value of x 3 and value of y_var 8 \n",
      "value of x 4 and value of y_var 16 \n",
      "value of x 5 and value of y_var 32 \n",
      "value of x 6 and value of y_var 64 \n",
      "value of x 7 and value of y_var 128 \n",
      "value of x 8 and value of y_var 256 \n",
      "value of x 9 and value of y_var 512 \n",
      "value of x 10 and value of y_var 1024 \n",
      "value of x 11 and value of y_var 2048 \n",
      "value of x 12 and value of y_var 4096 \n",
      "value of x 13 and value of y_var 8192 \n",
      "value of x 14 and value of y_var 16384 \n",
      "value of x 15 and value of y_var 32768 \n",
      "value of x 16 and value of y_var 65536 \n",
      "value of x 17 and value of y_var 131072 \n",
      "value of x 18 and value of y_var 262144 \n",
      "value of x 19 and value of y_var 524288 \n",
      "value of x 20 and value of y_var 1048576 \n",
      "value of x 21 and value of y_var 2097152 \n",
      "value of x 22 and value of y_var 4194304 \n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "import threading\n",
    "y_var=1\n",
    "lock_var=threading.Lock()\n",
    "def test1(x):\n",
    "    global y_var\n",
    "    with lock_var:\n",
    "    \n",
    "        y_var=y_var*2\n",
    "        print(\"value of x %d and value of y_var %d \" %(x,y_var)) \n",
    "        time.sleep(1)\n",
    "thread1=[threading.Thread(target=test1,args=(a,)) for a in [1,2,3,4,5,6,7,8]]\n",
    "thread2=[threading.Thread(target=test1,args=(b,)) for b in [9,10,11,12,13,14,15]]\n",
    "thread3=[threading.Thread(target=test1,args=(c,)) for c in [16,17,18,19,20,21,22]]\n",
    "for s in thread1:\n",
    "    s.start()\n",
    "for m in thread2:\n",
    "    m.start()\n",
    "for n in thread3:\n",
    "    n.start()\n",
    "   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b4aa2bc9-98d0-4812-8b23-ce07e2a18121",
   "metadata": {},
   "outputs": [],
   "source": [
    "#so with the help of lock multiple threads are running simultaneously and access to different shared resources."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8691ae57-c6fc-40f7-94c3-ba023e7f0efe",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dfd9ae40-f750-409f-9e10-55cfbc66cef5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
